load_config:
    task_name: "Text-to-Speech"
    functions: "Description Speech Generation"
    model_hf_path: "coqui/XTTS-v2"
    speakers_dir_path: "assets/audios/speakers"
    model_dir_path: "src/modules/text_to_speech/xtts_v2"
    language: "en"
    gpt_cond_len: 3
    specs:
        cpu:
            use_gpu: False
        gpu_low:
            use_gpu: False
        gpu_high:
            use_gpu: True

warm_up_config:
    text: "It took me quite a long time to develop a voice and now that I have it I am not going to be silent."
    output_wav_path: "assets/audios/sample.wav"